server:
  port: 8021
  ssl:
    enabled: true
    key-alias: apigateway
    key-store-type: PKCS12
    key-store: "D:/architect/store/apigateway-keystore.p12"
    key-store-password: changeit
    trust-store-type: JKS
    trust-store: "D:/architect/store/apigateway-truststore.jks"
    trust-store-password: changeit
    client-auth: need

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: process-service
              uri: lb://process-service
              predicates:
                - Path=/process/**

            - id: data-service
              uri: lb://data-service
              predicates:
                - Path=/data/**

            - id: auth-server
              uri: lb://auth-server
              predicates:
                - Path=/auth/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true