server:
  port: 8021

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/auth/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: process-service
              uri: lb://process-service
              predicates:
                - Path=/process/**

            - id: data-service
              uri: lb://data-service
              predicates:
                - Path=/data/**

            - id: auth-server
              uri: http://localhost:8085
              predicates:
                - Path=/auth/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true