eureka-server:
  port: 8761

auth-server:
  port: 8024

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:${eureka-server.port}/eureka