#Common properties of microservices.
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${auth-server.port}/oauth2/jwks
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  redis:
    host: localhost
    port: 6379
    password: user
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/test   #mongodb://<username>:<password>@<host>:<port>/<database>
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Architect;encrypt=true;trustServerCertificate=true;
    username: sa    #System Administrator
    password: StrongPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always