server:
  port: 8023
  servlet:
    context-path: /process

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  redis:
    host: localhost
    port: 6379
    password: user