server:
  port: 8023
  servlet:
    context-path: /process

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user