services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Main AMQP port
      - "15672:15672"  # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-server
    restart: unless-stopped
    ports:
        - "8080:8080"   # Jenkins web UI
        - "50000:50000" # Agents port
    volumes:
        - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: