services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Main AMQP port
      - "15672:15672"  # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-server
    restart: unless-stopped
    ports:
        - "8080:8080"   # Jenkins web UI
        - "50000:50000" # Agents port
    volumes:
        - jenkins_home:/var/jenkins_home

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    hostname: mssql_host
    restart: unless-stopped
    mem_limit: 2g   # MSSQL requires at least 2GB of RAM to start efficiently
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y   # Accept End-User License Agreement
      - MSSQL_SA_PASSWORD=StrongPassword123!  # Change this!
      - MSSQL_PID=Developer # Options: Developer, Express, Standard, Enterprise
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - db_network

volumes:
  jenkins_home:
  mssql_data:

networks:
  db_network:
    driver: bridge